version: '3'
services:
    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        env_file: .env
        ports:
            - '$NGINX_PORT:80'
        networks:
            - internal
        volumes:
            - ./web/:/var/www/html/
            - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
    php:
        image: php:fpm-alpine
        env_file: .env
        networks:
            - internal
        volumes:
            - ./web/:/var/www/html/
networks:
    internal:
        driver: bridge
