version: '3'
services:
    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        env_file: .env
        ports:
            - '$NGINX_PORT:80'
        networks:
            - internal
            - web
        volumes:
            - ./web/:/var/www/html/
    php:
        build:
            context: .
            dockerfile: php/Dockerfile
        env_file: .env
        networks:
            - internal
        volumes:
            - ./web/:/var/www/html/
networks:
    internal:
        driver: bridge
    web:
        external: true
